# Site settings
title: zangxin Blog
SEOTitle: zangxin Blog
header-img: img/home-bg.jpg
email: "caiqingsong51@gmail.com"
description: "记录 Java、Web 开发、数据库与哲学阅读笔记"
keyword: "Java, Spring, Web 开发, 数据库, 哲学, 读书笔记"
url: "https://zangxin.top"
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
lang: zh-CN

# Publish posts or collection documents with a future date.
future: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      header-mask: 0.35

# SNS settings
RSS: false
weibo_username: 
zhihu_username: 
github_username: zangxin51
twitter_username: 
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink:  /:year-:month-:day-:title/
exclude:
  [
    ".bundle",
    ".githooks",
    "_doc",
    "Gemfile",
    "Gemfile.lock",
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "package-lock.json",
    "Rakefile",
    "README.md",
    "README.zh.md",
    "scripts",
    "vendor",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
plugins: []

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username:

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: #"UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar: false
sidebar-about-description: "记录代码、阅读与思考"
sidebar-avatar:

# Featured Tags
featured-tags: false # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#5045bb"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: []
